### ISSUE TITLE
Julia documentations incomplete

### ISSUE THREAD

**Issue by hachikujimayoi298** [freeCodeCamp/devdocs#1082]
It seems all classes and methods in Base and Core are missing.

**Comment by scherepn** [comment]
The Julia scraper deliberatly removes references to "Base" from the name records of classes and methods within it. A search of "Core" in the current Julia 1.5 documentation on devodcs returns dozens of references, so this may have been fixed with a recent update.

I'm not a Julia developer and this decision (strip out "Base") appears to have been made by the original author of the scraper. We can change it, but is it the right thing to do?

**Comment by simon04** [comment]
Only the "Base." namespace is missing? Probably, because this namespace may be used without "Base."?

The following entries are available:

- https://devdocs.io/julia~1.6/base/math/index#Base.log2
- https://devdocs.io/julia~1.6/base/base/index#Core.eval

Closing this issue...
