### ISSUE TITLE
MDN Scraper is Bad

### ISSUE THREAD

**Issue by NotWearingPants** [freeCodeCamp/devdocs#1127]
The MDN scraper misses a lot of pages in MDN.

As you can see in this page: https://devdocs.io/dom/element
almost all of the links inside it are external links, even though they link to inside MDN itself.
This is especially true for the links in the compatibility table at the bottom.

Also in this page: https://devdocs.io/dom/workerglobalscope/onerror
there are 4 links, of which the 2 who are not working are redirects, which may be one cause of the problem I assume, although not all problematic links are redirects.

If you could give me some code pointers I'd be happy to try and solve this myself, but I'm not sure how to debug it.

**Comment by j-f1** [comment]
Sorry for the delay in replying!

This is due to several factors:

1. Some of the links are “red links” which are links to pages which don’t exist. A fix would be to remove these links when cleaning the HTML.
1. “This is especially true for the links in the compatibility table at the bottom.” I think that’s a bug.
1. Events are in a separate docset. I opened a PR a while ago to allow docs to link to each other but the other maintainers decided that the downsides of the approach I used were greater than the benefits. See #238 
1. I think the redirect thing is a bug.

The relevant files are in [`lib/docs/scrapers/mdn`](https://github.com/freeCodeCamp/devdocs/tree/master/lib/docs/scrapers/mdn) and [`lib/docs/filters/mdn`](https://github.com/freeCodeCamp/devdocs/tree/master/lib/docs/filters/mdn).
