### ISSUE TITLE
devdocs can not open any page, can't install any offline file

### ISSUE THREAD

**Issue by JarodChen** [freeCodeCamp/devdocs#1327]
![page can not load](https://user-images.githubusercontent.com/11836337/99273380-e8f25100-2863-11eb-937e-28e41650205c.PNG)
![offline](https://user-images.githubusercontent.com/11836337/99273384-ea237e00-2863-11eb-9be7-c6eb08f3e37f.PNG)

**Comment by simon04** [comment]
I cannot reproduce. Maybe yet another dubious CDN issue?

**Comment by ojeytonwilliams** [comment]
I can't reproduce it either.  @JarodChen is it possible that MaxCDN is blocked where you are?

**Comment by JarodChen** [comment]
@ojeytonwilliams @simon04 
Thank you！
Yes, we are in China. It looks like what you deduce

**Comment by subchen** [comment]
Same issue for me for several months.

**Comment by MasterEnoc** [comment]
@JarodChen @subchen  Devdocs has changed the infraestructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved

**Comment by JochenLutz** [comment]
I also get this error, even after the latest update.

**Comment by simon04** [comment]
Would you share the output on the browser console, please?

**Comment by JochenLutz** [comment]
![screenshot developer tools](https://user-images.githubusercontent.com/8270973/108416802-7eb8c600-722f-11eb-8840-91040daab954.png)

The last two error messages roughly translate to “cross-origin request blocked: the same-source policy forbids reading external resources from https://documents.devdocs.io/ruby~2.7/uri.html?1605253532. (Reason: CORS request failed). [More Information]“ and “Error loading 'https://documents.devdocs.io/ruby~2.7/uri.html?1605253532'. A ServiceWorker called FetchEvent.respondWith() with a promise that was rejected with 'TypeError: NetworkError when attempting to fetch resource.'.”

**Comment by simon04** [comment]
Do you use any extensions blocking access to different domains (uMatrix comes to my mind)? I cannot reproduce on Firefox 85.0.2 (64-bit).

**Comment by nhcarrigan** [comment]
Also unable to reproduce in Chrome Version 88.0.4324.182

**Comment by JochenLutz** [comment]
No blocking add-ons–custom tracking protection settings in Firefox, but I just checked with setting set to standard–still the same issue.

I then deactivated all add-ons and reactivated them one-by-one: the culprit is [User-Agent Switcher](https://addons.mozilla.org/de/firefox/addon/uaswitcher/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search).

I checked another [User-Agent Switcher and Manager](https://addons.mozilla.org/de/firefox/addon/user-agent-string-switcher/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) add-on. With this add-on, I can't reproduce the issue.
