### ISSUE TITLE
Difficulty scraping browser compatibility data

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/devdocs#1506]
MDN has changed how they populate the browser compatibility table.  It is generated in the browser, not served as part of the html.  As a result, scraping those pages is quite challenging.  Ideally we would like to include the table in DevDocs, as it is useful information, and any ideas on how to achieve this would be very welcome!

Original discussion here: https://github.com/freeCodeCamp/devdocs/pull/1473#discussion_r567139875_

**Comment by MasterEnoc** [comment]
I read https://github.com/mdn/browser-compat-data, which is the API of the compatability tables data. Currently this API is only supported for NodeJs, however, it can be use directly since all the data is found in JSON files.

The possible solution I have thought are:

- Download the needed Json files from the [compatibilty tables repo](https://github.com/mdn/browser-compat-data), retrieve the data of the tables and add the tables while scraping (see https://github.com/mdn/browser-compat-data/blob/main/api/Document.json, this is the JSON file with all the compatibility data of the DOM).
- I remember someone talk about JS scrapers, this API could be added to those scrapers (this is a future solutions since devdocs currently does not support js scrapers currently).
- Search for other projects that have a REST API with the data provided by MDN, make requests while scraping and add the tables (see https://github.com/mdn/browser-compat-data#projects-using-the-data).

**Comment by simon04** [comment]
I've just noticed again that we also have https://devdocs.io/browser_support_tables/ rendering data from https://caniuse.com/

**Comment by simon04** [comment]
Fixed via https://github.com/freeCodeCamp/devdocs/pull/1514, thank you, @MasterEnoc.
