### ISSUE TITLE
datetime link to mozzila is broken

### ISSUE THREAD

**Issue by AbhinavAchha** [freeCodeCamp/devdocs#1523]
The link to datetime attribute in html located in https://devdocs.io/html-attributes/ is broken.

please update to the correct link which is https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

**Comment by ojeytonwilliams** [comment]
Thanks for the report @AbhinavAchha.  The problem is that the page this is sourced from, https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes, has a broken link to datetime.  The correct link is https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#attr-datetime

@freeCodeCamp/devdocs any idea how easy it would be to create an exception in the scraper?

**Comment by j-f1** [comment]
This should probably be fixed on MDN’s side (see issue linked above)

**Comment by simon04** [comment]
Fixed on MDN. Fixed with the recent doc updates, see #1514.
