### ISSUE TITLE
[C++] Outdated documentation

### ISSUE THREAD

**Issue by glcraft** [freeCodeCamp/devdocs#1560]
# Documentation style bug

## Summary

The C++ documentation is outdated. I looked at the scraper file and it seems to download the first Archive file [here](https://en.cppreference.com/w/Cppreference:Archives).

The first book is the official book from June 2019. But the most updated book is the unofficial one (October 2020) available on the same page.

There is a huge difference between these two documentations as [C++20 was finalized and approved on September 2020](https://isocpp.org/blog/2020/09/cpp20-approved-herb-sutter).

The unofficial documentation should be prioritized until the official one is updated.

**In next sections, i'm taking the "Concept library (C++20)" page for example.**

## Actual style
![image](https://user-images.githubusercontent.com/6421451/121275143-4f0bf780-c8cc-11eb-808c-426f574db65b.png)

## Expected style
![image](https://user-images.githubusercontent.com/6421451/121275060-19ffa500-c8cc-11eb-9d0e-fb02c8afe0a2.png)

**Comment by simon04** [comment]
The repository of the unofficial documentation, https://github.com/PeterFeicht/cppreference-doc, reports that "This branch is 74 commits ahead, 41 commits behind p12tic:master". It seems that both repositories are being updated independently?

As I'm not concerned with C++ development, I'd like to hear a second opinion whether or not to replace the official with an unofficial documentation...

**Comment by MasterEnoc** [comment]
The cppreference page has newer documentation than the one in Devdocs, looks like it received an update in 2020 and devdocs has the 2019 version. It would be better to update, since the current documentation looks more like the unofficial one, but the cppreference does not mentioned if the current documentation in the page is from the unofficial one or not. The `get_latest_method` of cpp scraper is not scrapping the most accurate page to know if the documentation is up to date or not.

**Comment by glcraft** [comment]
Is it possible to make a doc archive of cppref by ourself from their repository ? In this case we could have the most updated doc.

**Comment by MasterEnoc** [comment]
@glcraft I want to add the c++20 documentation but I have some doubs if I should scrape the web site or use the unofficial html files. 

Looks at this:

This is a list of the c++ libraries from [cpp's page](en.cppreference.com/w/cpp/header)
![image](https://user-images.githubusercontent.com/52229226/123189202-a11b5400-d45a-11eb-90d5-4712ad4d7a15.png)

This is a list of the c++ libraries from the unofficial html files:
![image](https://user-images.githubusercontent.com/52229226/123189294-cb6d1180-d45a-11eb-9abb-893e47dc70ad.png)

The unofficial html files are missing two libraries (stacktrace and source_location) and I do not know if more documentation is missing. Do you think it would be better to scrape the web page (since it looks like it has more documentation)?

**Comment by glcraft** [comment]
I think it's better to scrape the website, which is constantly updated and then official.
I mentioned the unofficial one because in devdocs source code, it downloads the docs on cppref archives.
