### ISSUE TITLE
position arguments and data type are not seperated by space.

### ISSUE THREAD

**Issue by atmadeep** [freeCodeCamp/devdocs#1602]
# Bug report
There is no space between the positional argument (x,y, etc) and the beginning of the description. This is causing some confusion. 

## OS information
Not particular to any os

## Steps to reproduce
Visit the function documentation of any library related to python (matplotlib, seaborn etc)
![devdocs](https://user-images.githubusercontent.com/22106111/131565284-17fd95c0-9734-4586-b2b8-97ec471fa836.png)

**Comment by simon04** [comment]
I don't understand this bug report. Please highlight the problem on the screenshot. What is the expected behaviour? Please double-check whether the problem is also present in the upstream documentation.

- https://devdocs.io/matplotlib~3.4/_as_gen/matplotlib.pyplot.scatter
- https://matplotlib.org/3.4.1/api/_as_gen/matplotlib.pyplot.scatter.html
