### ISSUE TITLE
node.js doc internal links often wrong

### ISSUE THREAD

**Issue by smilingthax** [freeCodeCamp/devdocs#1721]
# node.js internal links

E.g.: `https://devdocs.io/node/fs#fs.opendirSync()`:  
* The link at `Returns: <fs.Dir>`
* points to `https://devdocs.io/node/fs#class-fsdir`, which is not helpful.
* The correct link would be `https://devdocs.io/node/fs#fs.Dir`.

This happens for nearly all internal links.

**Comment by simon04** [comment]
@MasterEnoc, I think this issue is related to your change [1ac3dd93ddeaa0dadf7eb1faf4639bac1c53287d](https://github.com/freeCodeCamp/devdocs/commit/1ac3dd93ddeaa0dadf7eb1faf4639bac1c53287d#diff-f48320087e0ab53997b664233cd817aca4188606884f6e766650f29ac89e1865R36) (overriding the element id with a different id generated from the name).
