### ISSUE TITLE
Show Source is broken for Ruby 3.2 documentation

### ISSUE THREAD

**Issue by Birdie0** [freeCodeCamp/devdocs#1922]
**Describe the bug**

Show source feature doesn't work for Ruby 3.2.0 documentation

**To Reproduce**

1. Go to any method documentation for Ruby 3.2, for example: [Hash#keys](https://devdocs.io/ruby~3.2/hash#method-i-keys)
2. Click on 'Show source' on the right of method header
3. See error

**Expected behavior**

Method source showed below header in the way it works for [3.1](https://devdocs.io/ruby~3.1/hash#method-i-keys) and older.

![image](https://user-images.githubusercontent.com/7945905/216566200-a48d8952-d0fc-4805-be69-3f87487da6ed.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/7945905/216563538-b665c9f0-3762-4fbf-ba76-7aaa16b19681.png)

**Desktop:**

 - OS: Windows 10
 - Browser: chrome
 - Version: 109

**Additional context**

Tried both resetting and using different browser, didn't solve the issue.

**Comment by j-f1** [comment]
It looks like the underlying issue is that the Ruby 3.2 docs wrap the `method-heading` in an additional `method-header` element, so the JS can’t find the relevant source code block. One way to fix this would be for the scraper to remove that wrapper. Another option would be for the JS to look for the `.method-detail` element at any distance above the clicked link, then start looking for the code block from there.
