### ISSUE TITLE
C++ Page not found (https://devdocs.io/cpp/chrono/year_month_day/operator_days)

### ISSUE THREAD

**Issue by kkzi** [freeCodeCamp/devdocs#1999]
# Bug report

## OS information
Windows 10 / Edge 113

## Steps to reproduce

1. access this url [year_month_day](https://devdocs.io/cpp/chrono/year_month_day)
1. search `operator sys_days`
2. click this url, forward to url (https://devdocs.io/cpp/chrono/year_month_day/operator_days) , we got 404 page not found
 

## More resources

![image](https://github.com/freeCodeCamp/devdocs/assets/34122458/75cdd21e-c65e-4071-95e7-851b974113ee)

![image](https://github.com/freeCodeCamp/devdocs/assets/34122458/8e697d2b-e551-49df-b9bb-27e1055c4abb)

**Comment by thewheat** [comment]
I believe this is due to 
- the formating of names here https://github.com/freeCodeCamp/devdocs/blob/0c1719eb030d8f8e89df8153a7b5d235de3376c8/lib/docs/filters/cpp/entries.rb#L57-L63
- and ignoring duplicate names https://github.com/freeCodeCamp/devdocs/blob/0c1719eb030d8f8e89df8153a7b5d235de3376c8/lib/docs/filters/cpp/entries.rb#L74-L79
- generating a page for https://en.cppreference.com/w/cpp/chrono/year_month_day/operator_days results in `std::chrono::year_month_day::operators` (shown below in some debug name output I added to the code)

```
thor docs:page cpp  /chrono/year_month_day/operator_days --verbose --debug
Request: en.cppreference.com/w/cpp/chrono/year_month_day/operator_days                                                                                                [200] [1130ms]
Filter: ApplyBaseUrl                                                                                                                                                           [0ms]
Filter: Container                                                                                                                                                              [3ms]
Filter: Cppref::FixCode                                                                                                                                                        [3ms]
Filter: CleanHtml                                                                                                                                                             [28ms]
Filter: NormalizeUrls                                                                                                                                                          [6ms]
Filter: InternalUrls                                                                                                                                                          [18ms]
Filter: NormalizePaths                                                                                                                                                         [2ms]
Filter: ParseCfEmail                                                                                                                                                           [2ms]
name: std::chrono::year_month_day::operators 
```
- `std::chrono::year_month_day::operators` already exists on a different page https://devdocs.io/cpp/chrono/year_month_day/operator_arith / https://en.cppreference.com/w/cpp/chrono/year_month_day/operator_arith

- I believe the rationale for the renaming is due to pages like this https://en.cppreference.com/w/cpp/atomic/atomic/operator_arith so `std::atomic<T>::operator++,++(int),--,--(int)` translates to `std::atomic::operators (int)` as seen here https://devdocs.io/cpp/atomic/atomic/operator_arith


Will need to think of a workable naming convention that prevents duplicates

**Comment by simon04** [comment]
Fixed with any of the various C++ scraper improvements.
