### ISSUE TITLE
Include search aliases in the docs.json file

### ISSUE THREAD

**Issue by manishrc** [freeCodeCamp/devdocs#2309]
https://documents.devdocs.io/docs.json currently does not include the search aliases as defined in https://github.com/freeCodeCamp/devdocs/blob/5c82069d893bc8dce505f421c6cf05135a593c33/assets/javascripts/models/entry.js#L20-L54

https://github.com/freeCodeCamp/devdocs/blob/5c82069d893bc8dce505f421c6cf05135a593c33/lib/docs/core/doc.rb#L81-L87

Including the search aliases will help external tools integrate better with DevDocs. 

Reference issue https://github.com/raycast/extensions/issues/14100#issuecomment-2298802285

**Comment by chrisgrieser** [comment]
related: #2210

**Comment by simon04** [comment]
Hi @djpowers, I'm very sorry for the long outstanding reply. I found it very hard to troubleshoot and fix this issue. It seems that https://github.com/freeCodeCamp/devdocs/commit/ee145d748f61a679084e8c1cb754511e62a4f9d4 mostly fixed the issue?

```sh
> curl -sL "https://devdocs.io/docs.json" | grep "alias" | grep -v "null" | uniq | count
31
```

The problem was twofold: for one thin, doc slugs containing a version (such as `python~3.13`) were not handled; for the other, some alias definitions did not match a doc slug (due to a `.js` suffix for instance).

Cheers!

**Comment by djpowers** [comment]
@simon04 no problem at all, thanks for taking another look! Confirming I'm seeing the additional alias values coming through now. I appreciate the extra context as well.
