### ISSUE TITLE
Electron like runner

### ISSUE THREAD

**Issue by Spy-Seth** [freeCodeCamp/devdocs#480]
Hey everyone,

I was using devdocs from a long time time from has Google Chrome web app. Now Chrome have disable his web app feature on desktop, I've lost my devdocs icon in my dock :( So much time loose to quickly see a doc. 

Has the [Firefox web app](https://marketplace.firefox.com/app/devdocs?src=search) is not available on all platform. I was thinking that you could easily generate an Electron like app for devdocs.

**Comment by luke3butler** [comment]
Everyone on OSX uses [devdogs](https://github.com/ragingwind/devdogs) 

[There's also this for Windows/Linux](https://github.com/egoist/devdocs-app)

**Comment by Spy-Seth** [comment]
Ho I've miss this!

**Comment by JaKXz** [comment]
You can also use [nativefier](http://npm.im/nativefier)

**Comment by gengjiawen** [comment]
Give this a try: https://github.com/gengjiawen/electron-devdocs/releases

**Comment by markbirbeck** [comment]
Yet another way...

...use [Sidewinder Viewer](https://github.com/markbirbeck/sidewinder-viewer). It's an Electron wrapper that takes a URL for a web app and executes it in Electron, handling a few bits and bobs like what happens when a link is clicked. Configuration can be set in the URL using XPointer syntax:

```shell
$ npm install -g sidewinder-viewer
$ sidewinder "https://devdocs.io#meta(width=1000,height=800)"
```

Since devdocs itself is doing all the caching and downloading then this 'just works'.

**Comment by jmerle** [comment]
I think this can be closed. Because of the solutions offered in the comments above and on the [wiki](https://github.com/freeCodeCamp/devdocs/wiki#plugins-and-extensions) I don't think there's a need for an "official" desktop application anymore.
