### ISSUE TITLE
Search by documentation (e.g. "r<tab>") does not always work

### ISSUE THREAD

**Issue by svoop** [freeCodeCamp/devdocs#59]
Typing a tag followed by hitting the tab key in the search field such as "ruby<tab>" or "r<tab>" does not always work. It's most notably broken on the initial page http://devdocs.io whereas on some subpages such as http://devdocs.io/ruby/array this feature works normally.

Tested on Firefox 26 (Mac and Win), Chrome 32 (Mac) and Safari 7 (Mac).

**Comment by pablobm** [comment]
I just came across this. Even though the functionality is not broken, I'd argue this is an usability problem.

In my case, I entered "Rust\<tab\>" and I got "Ruby / Minitest". The problem here is that, before pressing \<tab\>, Rust does appear on the list, making it look like a selectable choice. The documentation panel does show a message explaining that the Rust docs haven't been enabled, but when you are navigating you are not looking at that: your eyes are on the nav panel.

A small pill saying "disabled" or similar, next to the documentation name, on the navigation panel, would make this more obvious.

**Comment by Thibaut** [comment]
@pablobm Thanks for the feedback! I added an "enable" link to disabled doc search results :)

![devdocs api documentation 2015-12-07 08-05-02](https://cloud.githubusercontent.com/assets/17579/11627575/7ff506e2-9cb9-11e5-90fd-a6b302abea82.png)

**Comment by pablobm** [comment]
:+1: :boom: :dancer: :tada: :smile:
