### ISSUE TITLE
Switch to a Service Worker

### ISSUE THREAD

**Issue by j-f1** [freeCodeCamp/devdocs#774]
[It looks like](https://jakearchibald.github.io/isserviceworkerready/) Service Workers are supported on the latest versions of all of the browsers.

Some ideas:

- automatically cache anything the user looks at while online
- use [Web Push](https://devdocs.io/browser_support_tables/push-api) to update docsets in the background even if DevDocs isn’t open (maybe if they disable auto-updates, we could prompt them with a desktop notification)
- preload linked pages when the user tabs to a link to them, or hovers over the link
- preload the top few search results for instant loading

If we use Service Workers, we won’t have to do anything different when offline vs online — just fetch the docset from the URL, and the worker will proxy it to the cache, even if the user is online (we can also fetch an updated version if the cached copy is out-of-date and store it for the next time the page gets loaded).

Demo will be available [here](https://fortunate-jumper.glitch.me) at some point (it’s still on AppCache right now)

**Comment by cglong** [comment]
It looks like, [as of EdgeHTML 17.17063](https://blogs.windows.com/msedgedev/2018/02/06/welcoming-progressive-web-apps-edge-windows-10/#mBXG9JCltyA7IOQ7.97), Service Workers are enabled by default 😄

It'd be good to support this, as Service Workers are [a requirement for automatic indexing into the Microsoft Store](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/microsoft-store#automatic-pwa-importing-with-bing).

**Comment by j-f1** [comment]
Updated. Thanks!

**Comment by jmerle** [comment]
[Since Chrome 68](https://developers.google.com/web/updates/2018/07/nic68#a2hs) the "Add to homescreen button" is no longer available for manual use on Android. Instead, websites can trigger an "Add to homescreen" dialog if the website meets certain [criteria](https://developers.google.com/web/fundamentals/app-install-banners/#criteria). One of these criteria is registering a service worker with a `fetch` event handler, so that's another vote towards this issue.

**Comment by ryanburnette** [comment]
Thumbs up to converting devdocs from appcache to serviceworkers.

**Comment by eloyesp** [comment]
I would vote against that, because I like this project and [Service Workers might be insecure][1] so are disabled by many people (me included).

[1]: https://security.stackexchange.com/questions/202197/privacy-tracking-concerns-regarding-service-workers

**Comment by ryanburnette** [comment]
The method the site currently uses to provide offline functionality is on its way to being deprecated. If there isn't a move to service workers we'll probably lose offline functionality.

It won't be terribly hard to do anyway. Once the site is cached for offline use, the rest of the data is installed into localStorage.

**Comment by abraham** [comment]
@eloyesp you mention "insecure" except the linked question is regarding privacy. Privacy and security are different (although related).

Regarding the privacy concerns of service workers, there is negligible risk. Service workers get woken up to handle two types of events: `fetch` and `push`.

- `fetch` means that an HTTP request is already being made and can send data to a server without a SW existing.
- `push` means that the server is sending a push notification that the user had to have opted into and the app has to show browser notification so the user knows the app is active. Being opt-in the privacy risk is minimal.

SWs don't fundamentally change the security and privacy models of the web. Origin restrictions, CORS, etc are all still in effect.

**Comment by jwkicklighter** [comment]
Just wanted to chime in that I'd personally like this so that the site can be installed as a standalone PWA on desktop environments as well.

**Comment by jmerle** [comment]
I will start working on this next week, although it might take a while to complete because it's quite a big change. I will comment on this issue when I make significant progress and/or when I get a working demo with service workers online.

**Comment by jmerle** [comment]
Time for an update. I have successfully replaced the App Cache with a Service Worker in [jmerle/devdocs#service-worker](https://github.com/jmerle/devdocs/tree/service-worker). There is a live demo running at [sw.devdocs.jmerle.dev](https://sw.devdocs.jmerle.dev).

This change to a Service Worker also means that DevDocs will be an installable PWA.

I have already tested the changes on the following browsers:
- Chrome 75 on Ubuntu 18.04
- Firefox 67 on Ubuntu 18.04
- Opera 62 on Ubuntu 18.04
- Chrome 75 on Android 9
- Firefox 67 on Android 9

Because I do not have access to any Windows or Apple machines at the moment and don't want to deploy such a change without knowing it works on all our supported platforms, it would be really nice if some people can test the changes on a recent version of Edge on Windows, Safari on macOS and Safari on iOS.

To help test the changes, do the following:
1. Go to [sw.devdocs.jmerle.dev](https://sw.devdocs.jmerle.dev/).
2. Wait a few seconds for all assets to be cached and then go offline (either via the OS or via the browser's DevTools).
3. Refresh the page.
4. If everything goes well, DevDocs loads as usual (even though you're offline).
5. (skip on mobile) Resize the sidebar and refresh again.
6. (skip on mobile) If everything goes well, the resizing of the sidebar is persistent even when offline (something that isn't the case with the current App Cache approach).
7. Comment on this issue with the browser version, the OS and whether everything went well or not.

cc @cglong @j-f1

**Comment by j-f1** [comment]
Works on Safari on iOS 12.3.1 🎉

**Comment by j-f1** [comment]
And on Safari 12.1 on macOS 10.14.4.

**Comment by jmerle** [comment]
Sweet, thanks! If someone can confirm it works on Edge I'll open a PR.

**Comment by cglong** [comment]
@jmerle I can verify with Edge in an hour or two 🙂

**Comment by cglong** [comment]
@jmerle, just tried it out using EdgeHTML 18.18362 on Windows 10 Version 1903. Looks great; thank you for taking the time to implement this! A few notes:

* Refreshing the page while offline successfully loaded the page
* Resizing the sidebar and refreshing was persistent
* Attempting to navigate to any page within DevDocs while offline rendered the below error, even if I had previously visited the page

I could definitely have been doing something wrong (or perhaps this was intentional at this time), so please let me know if there's anything else I can do to help debug :)

![image](https://user-images.githubusercontent.com/137214/61014245-540c4900-a33b-11e9-9431-c3c04ddc4781.png)

**Comment by jwkicklighter** [comment]
@cglong I haven't looked at the inner-workings, but did you try marking some docs as available for offline in the settings, rather than just visiting them once?

**Comment by jmerle** [comment]
@cglong thanks for testing it on Edge! The error you see can indeed be caused by not having downloaded the documentation for offline usage, although our current App Cache version of DevDocs does seem to support loading documentation entries without downloading them for offline usage when you have visited the entry before. While implementing something similar with service workers is possible, I'll leave that open for a future PR. I have updated the error message slightly to tell users to install documentations before going offline and have created a PR at #1022:

![](https://i.imgur.com/VZ8FMal.png)

**Comment by cglong** [comment]
@jwkicklighter @jmerle Oh duh, I forgot I had to do this 😅 Sorry! I just tried requesting the docs be installed and verified everything works as expected in Edge 😎

**Comment by jwkicklighter** [comment]
@jmerle thanks for getting this done so quickly, it was the biggest feature I've wanted to see since I started using devdocs!

**Comment by jmerle** [comment]
The service worker changes are now live on [devdocs.io](https://devdocs.io/) :tada:

**Comment by trysten** [comment]
Can this issue be closed, since Service Worker is implemented?

**Comment by ojeytonwilliams** [comment]
Yes, this can be closed. Thanks, @trysten.
