### ISSUE TITLE
make contact with MDN

### ISSUE THREAD

**Issue by alexch** [freeCodeCamp/devdocs#785]
MDN (Mozilla Developer Network) is a very useful and deep documentation site; unfortunately, its depth makes it troublesome to parse and scrape. It would be great to make contact with someone inside Mozilla to figure out ways we can more easily be informed of changes, both to save our QA/dev time and to lighten the network load on MDN itself during scraping. 

Like maybe a site map, or archive download, or guidelines on good times/rates to scrape...

**Comment by PhilippeVay** [comment]
Hi,

AFAIK the best place to get in contact with MDN would be their [Discourse](https://discourse.mozilla.org) in the MDN section.

**Comment by hofrob** [comment]
There's a sitemap available: https://developer.mozilla.org/sitemap.xml which refers to the various translations, for example: https://developer.mozilla.org/sitemaps/en-us/sitemap.xml.gz

From a first glance it could be split into at least these categories:

* Web (API, Accessibility, CSS, HTML, HTTP, JavaScript)
* WebAssembly
* Games
* Glossary

**Comment by hofrob** [comment]
This is not really obvious in this app, but MDN documentation is already part of devdocs.io. So this issue can probably be closed. I'd just suggest prefixing MDN to the documentations that are scraped from Mozilla. Just calling them JavaScript or XSLT does not really tell a user what kind of documentation this is.

**Comment by ojeytonwilliams** [comment]
I agree that this can be closed.

While I understand that it's not heavily advertised that the JavaScript section is scraped from MDN, they are cited at the bottom of each doc (at least they should be!).  The main reason, as I understand it, that we don't prefix the name for MDN docs is ease of searching.  For instance, if you search for REST, then Django REST Framework doesn't become the top link until you type 'restf' because of the presence of 'Django'.

Also, in a general sense, we're not aiming to provide the MDN JavaScript docs. We just want to provide JavaScript docs and MDN is an amazing resource that we can use.
