### ISSUE TITLE
C++ attributes parsing is wrong

### ISSUE THREAD

**Issue by mathbunnyru** [freeCodeCamp/devdocs#868]
For example, this page doesn't is not parsed correctly:
https://devdocs.io/cpp/container/array/empty

It should look like:
```
constexpr bool empty() const noexcept; |   | (since C++11) (until C++20)
[[nodiscard]] constexpr bool empty() const noexcept; |   | (since C++20)
```

It looks like:
```
constexpr bool empty(); |   | (since C++11) (until C++14)
constexpr bool empty() const; |   | (since C++14)
```

There was no standard when `empty()` was non-const and I'm pretty sure there was so such mistake in cppreference. So I think parsing is not done correctly when there are attributes like `[[nodiscard]]`.

**Comment by jmerle** [comment]
Because the cppreference is quite big, the DevDocs scraper scrapes the [offline HTML book](https://en.cppreference.com/w/Cppreference:Archives) instead of the website. The archives, both the official and the unofficial ones, do not have the `[[nodiscard]]` attribute, nor do they have the `noexcept` thing. The parser does seem to work correctly though, we'll just have to wait for an update to the offline version.

Side-by-side comparison (left is the online version, right is the latest unofficial offline version from August 19th):
![](https://i.imgur.com/JECvSwP.png)

**Comment by mathbunnyru** [comment]
@jmerle thank you, that explains a lot!

I've just downloaded html-book-20180819.zip from the link you gave me and I can confirm, that `[[nodiscard]]`, `noexcept` and `const` are correct right there. Maybe they updated the files without even telling about it?

@jmerle @j-f1 please, could you update devdocs documentation using this zip file?

**Comment by j-f1** [comment]
Unfortunately we don’t have access to the server, but we’re hoping to have that ability at some point and we’ll go through all the `docs/bug` issues then.

**Comment by jmerle** [comment]
@mathbunnyru you're right, the nodiscard attribute (and the other 2 things) do appear in the latest unofficial HTML book. The screenshot above was with the latest official version, I've edited the comment to remove my mistake.

I'll try tonight to see if the unofficial version works with the parser too. If it does, we can remove the bug classification for this issue and flag it as outdated documentation.

**Comment by jmerle** [comment]
The unofficial version works fine with the parser too, so it's just outdated documentation now.

![](https://i.imgur.com/1nR8WMV.png)

**Comment by mathbunnyru** [comment]
Great news, thank you! Waiting for an update.

**Comment by Thibaut** [comment]
Updated :) Thanks for the investigation @jmerle!
