### ISSUE TITLE
Add documentation for Chrome extension APIs

### ISSUE THREAD

**Issue by GaurangTandon** [freeCodeCamp/devdocs#950]
I really like using the DevDocs interface (and the excellent search facility!) for my daily JS/C++ coding. Now that I was about to resume some Chrome extension work, I was hoping (and really want) to request documentation for Chrome extension APIs on Devdocs.

Specifically, [`chrome.runtime`](https://developer.chrome.com/apps/runtime), [`chrome.extension`](https://developer.chrome.com/extensions/extension), [`chrome.contextMenues`](https://developer.chrome.com/extensions/contextMenus), and others.

Is it possible? Thanks!

**Comment by Kaijiro** [comment]
Hello there !

Thank you for your interest about DevDocs :) 

According to the [contributing guide](https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#requesting-new-documentations), @Thibaut would like you to use the [Trello Board](https://trello.com/b/6BmTulfx/devdocs-documentation) instead of opening an issue. If you know Ruby, you can create a branch and start adding your contribution to DevDocs, it would be very welcome since @Thibaut doesn’t have time to add many new docs these days.

**Comment by GaurangTandon** [comment]
Hi @Kaijiro , sorry for not reading the contributing guide properly. I'll open the request on the Trello Board. Unfortunately, my fluency with Ruby is little, so I guess I can't contribute much there.

Thanks for your prompt response!

**Comment by Kaijiro** [comment]
You're welcome ;)

It would be a nice occasion to train your fluency in Ruby if you'd like to :p
