### ISSUE TITLE
Android app? 

### ISSUE THREAD

**Issue by Merith-TK** [freeCodeCamp/devdocs#974]
Is it possible to write this in a way it can be used for Android?
I found a repository of code (somewhere here on github.com) that let's you turn any website into a android app.

Is it possible to do the same for devdocs.io? I rather like the mobile ui and think it would make a great app

**Comment by j-f1** [comment]
You should be able to install it as a PWA. Here’s an article with some instructions: https://www.techrepublic.com/article/how-to-use-progressive-web-apps-on-android/

Does this work for you?

**Comment by Merith-TK** [comment]
It worked via Firefox. But I was thinking of being able to download it from
the Android Play Store.

**Comment by j-f1** [comment]
See #274 for a similar previous discussion.

**Comment by j-f1** [comment]
Feel free to make an app! We’d be happy to feature it on the website.

**Comment by jmerle** [comment]
I'd also like to add that any "website to Android app" tool that you'll find will just give you an Android app where there is one [WebView](https://developer.android.com/reference/android/webkit/WebView) that displays the website. In other words, it would be a glorified browser that is only capable of accessing one website.

**Comment by Merith-TK** [comment]
The one I was looking at, would take offline HTML CSS and JS. And display
it in what is essentially a webveiw

**Comment by Merith-TK** [comment]
This is the software i was talking about
https://github.com/jakewp11/HTML5_Android_Template

But since the site isnt written in HTML, this wont work

**Comment by Merith-TK** [comment]
So, i made the app using Apache-Cordova

The Pre-Release of the app. it utilizes a `iframe` in HTML to completely load the webpage. first run requires internet to cache the site, subsequent runs act like the actual site
https://github.com/Merith-TK/devdocs_webapp/releases/tag/v0.1.1-alpha

The Apache-Cordova project.
https://cordova.apache.org/

**Comment by Merith-TK** [comment]
So here is where I'm stuck in my Android App Project.

Essentially, I'm trying to find out how to suppress the warning that shows its running in a WebVeiw, because it's annoying. I do not plan on distributing this on the play store without Creator Consent, 

I specifically would like to replace it with a Disclaimer that says that the application is what it is, a Web view to the main site for convenience as many people use web browsers that don't support the normal installation method that is "Official".

One of my Peers suggested I go inside the iFrame with JS and remove it, but I don't know much about JS.

I tried changing the UserAgent of the iframe, but that has failed. in every way.

I Have even tried the `UserAgent` plugin for Cordova, but there is no documentation on it so I don't know how to use it
https://github.com/LouisT/cordova-useragent
I plan on distributing the application via my Github Repo (linked in the previous Comment)

I have even tried to use the official Cordova inappbrowser plugin, which works and feels less jank than my current method used in `pre-release v0.1.1-alpha`

If Anyone wishes to help, please Respond and/or fork my repo

**Comment by maxloh** [comment]
> You should be able to install it as a PWA. Here’s an article with some instructions: https://www.techrepublic.com/article/how-to-use-progressive-web-apps-on-android/
> 
> Does this work for you?

Currently devdocs is not a PWA.

As far as I know, a PWA with proper service worker can be installed as a **APP** (but not a shortcut) in android with can be accessed offline and found in app drawer.

All you need is only a `manifest.json` file and a service worker JavaScript file in the root directory.

You can easily build a PWA in <http://www.pwabuilder.com/>, which comes from Microsoft.

**Comment by j-f1** [comment]
@maxloh we already [have a `manifest.json`](https://github.com/freeCodeCamp/devdocs/blob/master/public/manifest.json). We haven’t yet migrated to service workers, but application cache provides the same functionality to us.

**Comment by Merith-TK** [comment]
I will be honest, if I knew a more native way of building the application by using its native framework. I would

**Comment by Merith-TK** [comment]
My application is successfully built, and works just fine!
https://github.com/Merith-TK/devdocs_webapp/releases/tag/v1.0

@j-f1 @jmerle

**Comment by maxloh** [comment]
> @maxloh we already [have a `manifest.json`](https://github.com/freeCodeCamp/devdocs/blob/master/public/manifest.json). We haven’t yet migrated to service workers, but application cache provides the same functionality to us.

Maybe you need a service worker for the PWA to be installable in Chrome.

The application tab of Chrome says `Service worker is not registered or does not control the Start URL` and I cannot install DevDocs as an app in Chrome Windows and Android.

![image](https://user-images.githubusercontent.com/35831069/52796059-0c480500-30ae-11e9-9131-aef0963b1444.png)

**Comment by Merith-TK** [comment]
The android application is at release 1.1
The new release gives an Application Icon, and fixes ~~``(fixed totally on accident)``~~ an issue where any and all links go to the default web browser.

Now All EXTERNAL links go to webbrowser while all `devdocs.io/*` links stay in the app

**Comment by jmerle** [comment]
I appreciate the effort that you're putting into a 3rd party application, but I think this issue isn't the right place to keep a changelog of your application.

Furthermore, just because you got rid of the WebView warning doesn't mean it voids the message it displayed. I saw your todo list contained an item of getting (semi-)official support, which is something we probably can't give you. This is because by default a lot of modern standards are disabled in a WebView, and because the rendering engine the WebView uses can differ quite a lot between different phones (so a bug on one phone might not be reproducable on another with the same app).

I can not reproduce your bug in any modern browser (tried Chrome, Firefox and Chrome for Android on the latest stable versions). The message you're seeing is only shown if [`window.applicationCache` does not exist or it's status is not `UNCACHED`](https://github.com/freeCodeCamp/devdocs/blob/master/assets/javascripts/app/appcache.coffee#L6). Furthermore, the AppCache is disabled by default in a WebView and when writing a native app you need to call [`WebSettings.setAppCacheEnabled(true)`](https://developer.android.com/reference/android/webkit/WebSettings#setAppCacheEnabled(boolean)) before loading the page. I don't know the Apache Cordova specifics on this, but that might lead you on your way.

Another reason why it might work for you without AppCache enabled is that the default cache mode in a WebView makes it load cached resources when there is no network available (the default cache mode is [`LOAD_DEFAULT`](https://developer.android.com/reference/android/webkit/WebSettings.html#LOAD_DEFAULT), you can change it with [`WebSettings.setCacheMode()`](https://developer.android.com/reference/android/webkit/WebSettings.html#setCacheMode(int))).

I also think it's best to keep the Service Worker discussion in #774.

**Comment by Merith-TK** [comment]
Alright, I just felt like I'd wants to keep the developers of the original
service up to date to know if I accidentally overstep my boundaries.

**Comment by Merith-TK** [comment]
Okay, So I have moved to a more modern framework (kotlin)

And... I kinda need the squarelike icon... because of this icon
![ic_launcher](https://user-images.githubusercontent.com/10422110/53593453-a6e42180-3b4d-11e9-82c2-af6aaf9dfb03.png)
is ugly

**Comment by Merith-TK** [comment]
Ignore, this, just found the files via `f12`
